apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: env-helm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  namespace: kube-system
  name: env-helm-controller
subjects:
- kind: ServiceAccount
  name: env-controller
  namespace: default
