// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	gits "github.com/jiubian-cicd/env-controller/pkg/gits"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyPtrToGitsGitWebHookArguments() *gits.GitWebHookArguments {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*gits.GitWebHookArguments))(nil)).Elem()))
	var nullValue *gits.GitWebHookArguments
	return nullValue
}

func EqPtrToGitsGitWebHookArguments(value *gits.GitWebHookArguments) *gits.GitWebHookArguments {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *gits.GitWebHookArguments
	return nullValue
}
