// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	gits "github.com/jiubian-cicd/env-controller/pkg/gits"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyPtrToGitsGitPullRequest() *gits.GitPullRequest {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*gits.GitPullRequest))(nil)).Elem()))
	var nullValue *gits.GitPullRequest
	return nullValue
}

func EqPtrToGitsGitPullRequest(value *gits.GitPullRequest) *gits.GitPullRequest {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *gits.GitPullRequest
	return nullValue
}
