// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	gits "github.com/jiubian-cicd/env-controller/pkg/gits"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyPtrToGitsGitPullRequestArguments() *gits.GitPullRequestArguments {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*gits.GitPullRequestArguments))(nil)).Elem()))
	var nullValue *gits.GitPullRequestArguments
	return nullValue
}

func EqPtrToGitsGitPullRequestArguments(value *gits.GitPullRequestArguments) *gits.GitPullRequestArguments {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *gits.GitPullRequestArguments
	return nullValue
}
