// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	gits "github.com/jiubian-cicd/env-controller/pkg/gits"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnySliceOfGitsGitOrganisation() []gits.GitOrganisation {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]gits.GitOrganisation))(nil)).Elem()))
	var nullValue []gits.GitOrganisation
	return nullValue
}

func EqSliceOfGitsGitOrganisation(value []gits.GitOrganisation) []gits.GitOrganisation {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []gits.GitOrganisation
	return nullValue
}
